using System;
using System.Collections.Generic;
using System.Linq;

namespace KaijuGame.Entities
{
    public static class KaijuGenerator
    {
        public static Kaiju makeKaiju()
        {
            var rand = new Random();
            var mons = new Kaiju();

            //mons.size = KaijuDetails.Size[rand.Next(0, KaijuDetails.Size.Length)];
            mons.creature = KaijuDetails.Creatures[rand.Next(0, KaijuDetails.Creatures.Length)];

            //get material
            var key = KaijuDetails.Material.ElementAt(rand.Next(0, KaijuDetails.Material.Count())).Key;
            mons.material = KaijuDetails.Material[key][rand.Next(0, KaijuDetails.Material[key].Length)];
            if (mons.material != "skinless")
            {
                mons.material += " skinned";
            }

            //define characteristic
            key = KaijuDetails.Characteristic.ElementAt(rand.Next(0, KaijuDetails.Characteristic.Count())).Key;
            mons.characteristic = KaijuDetails.Characteristic[key][rand.Next(0, KaijuDetails.Characteristic[key].Length)];

            //define weapon
            key = KaijuDetails.Weapons.ElementAt(rand.Next(0, KaijuDetails.Weapons.Count())).Key;
            mons.weapon = KaijuDetails.Weapons[key][rand.Next(0, KaijuDetails.Weapons[key].Length)] + " " + key;

            KaijuDetails.getName(mons);

            return mons;
        }
    }

    public static class KaijuDetails
    {
        public static void getName(Kaiju monStar)
        {
            var randy = new Random();
            var frontCompounds = adjectives;
            var rearCompounds = adjectives;

            var ofXs = theXs;
            var arrayLength = 846;

            var firstName = randy.Next(1, arrayLength);
            var frontCompound = randy.Next(1, arrayLength);
            var rearCompound = randy.Next(1, arrayLength);
            var firstAdjective = randy.Next(1, arrayLength);
            var secondAdjective = randy.Next(1, arrayLength);
            var hyphenCompound = randy.Next(1, arrayLength);
            var theX = randy.Next(1, 1217);
            var ofX = randy.Next(1, 1217);
            var epithet = randy.Next(1, 100) <= 60;
            var hasFirstAdjective = randy.Next(0, 5) == 1;
            var hasSecondAdjective = randy.Next(0, 5) == 1;
            var hasHyphenCompound = randy.Next(0, 5) == 1;
            var hasOfX = randy.Next(1, 100) <= 60;

            monStar.nameMonster = getMonsterName(frontCompounds, rearCompounds, ofXs, firstName, frontCompound, rearCompound, firstAdjective, secondAdjective, hyphenCompound, theX, ofX, epithet, hasFirstAdjective, hasSecondAdjective, hasHyphenCompound, hasOfX);
            monStar.nameEnglish = getEnglishName(frontCompounds, rearCompounds, ofXs, firstName, frontCompound, rearCompound, firstAdjective, secondAdjective, hyphenCompound, theX, ofX, epithet, hasFirstAdjective, hasSecondAdjective, hasHyphenCompound, hasOfX);
        }

        private static string getMonsterName(string[,] frontCompounds, string[,] rearCompounds, string[,] ofXs, int firstName, int frontCompound, int rearCompound, int firstAdjective, int secondAdjective, int hyphenCompound, int theX, int ofX, bool epithet, bool hasFirstAdjective, bool hasSecondAdjective, bool hasHyphenCompound, bool hasOfX)
        {
            var monsterName = adjectives[firstName, 1] + " " + frontCompounds[frontCompound, 1] + rearCompounds[rearCompound, 1];
            if (epithet)
            {
                var tempString = "";
                if (hasFirstAdjective)
                    tempString = tempString + adjectives[firstAdjective, 1] + " ";
                if (hasSecondAdjective)
                    tempString = tempString + adjectives[secondAdjective, 1] + " ";
                if (hasHyphenCompound)
                    tempString = tempString + adjectives[hyphenCompound, 1] + " ";

                tempString = tempString + theXs[theX, 1];
                if (hasOfX)
                    tempString = tempString + " " + ofXs[ofX, 1];
                monsterName = monsterName + tempString;
            }
            return monsterName;
        }

        private static string getEnglishName(string[,] frontCompounds, string[,] rearCompounds, string[,] ofXs, int firstName, int frontCompound, int rearCompound, int firstAdjective, int secondAdjective, int hyphenCompound, int theX, int ofX, bool epithet, bool hasFirstAdjective, bool hasSecondAdjective, bool hasHyphenCompound, bool hasOfX)
        {
            var englishName = adjectives[firstName, 1] + " " + frontCompounds[frontCompound, 0] + rearCompounds[rearCompound, 0];
            if (epithet)
            {
                var tempString = " the ";
                if (hasFirstAdjective)
                    tempString = tempString + adjectives[firstAdjective, 0] + " ";
                if (hasSecondAdjective)
                    tempString = tempString + adjectives[secondAdjective, 0] + " ";
                if (hasHyphenCompound)
                    tempString = tempString + adjectives[hyphenCompound, 0] + " ";

                tempString = tempString + theXs[theX, 0];
                if (hasOfX)
                    tempString = tempString + " " + ofXs[ofX, 0];
                englishName = englishName + tempString;
            }
            return englishName;
        }

        public static string[] Size = new string[]
{
            "tiny",
            "small",
            "medium",
            "large",
            "huge",
            "gargantuan"
};

        public static string[] Creatures = new string[]
        {
            "alligator",
            "allosaurus",
            "ape",
            "aurochs",
            "baboon",
            "badger",
            "bat",
            "black Bear",
            "Blood Hawk",
            "boar",
            "brontosaurus",
            "brown Bear",
            "camel",
            "cat",
            "cave Bea",
            "cow",
            "crab",
            "crocodile",
            "deer",
            "deinonychus",
            "dimetrodon",
            "dragon",
            "eagle",
            "eagle",
            "elephant",
            "elk",
            "flying Snake",
            "frog",
            "fungus",
            "golem",
            "gorilla",
            "horse",
            "minotaur",
            "ooze",
            "ostritch",
            "ox",
            "polar Bear",
            "sloth",
            "slug",
            "snake",
            "spider",
            "squid",
            "tiger",
        };

        public static Dictionary<string, string[]> Material = new()
        {
            { "flesh", new string[] { "leathery", "skinless", "rash covered", "rotting" } },
            { "rock", new string[] { "limestone", "grantie", "obsidian", "pumice", "shale" } },
            { "gem", new string[] { "jade", "diamond", "gypsum", "pumice", "opal", "quartz", "jasper" } },
            { "metal", new string[] { "iron", "steel", "bronze", "tin", "copper", "aluminum", "gold", "silver", "titanium" } },
            { "clay", new string[] { "clay" } },
            { "glass", new string[] { "glass" } },
            { "wood", new string[] { "wood" } },
            { "refuse", new string[] { "refuse" } },
            { "ice", new string[] { "ice" } },
            { "wool", new string[] { "wool" } },
        };

        public static Dictionary<string, string[]> Characteristic = new()
        {
            { "changes colours", new string[] { "blur" } },
            { "eyes", new string[] { "compound eyes", "eye stalks", "eyeless" } },
            { "furry", new string[] { "furry" } },
            { "slimy", new string[] { "slimy" } },
            { "stinky", new string[] { "stinky" } },
            { "reflective", new string[] { "reflective" } },
        };

        public static Dictionary<string, string[]> Weapons = new()
        {
            { "teeth", new string[] { "razor sharp" } },
            { "spittle", new string[] { "tar", "oil", "lava", "steam", "acid", "alchohol" } },
            { "breath", new string[] { "fire", "cold", "lightning", "smoke", "poison" } },
            { "stinger", new string[] { "poisonous" } },
        };

        public static string[,] adjectives = new string[,] {{"ace", "alak"}, {"ageless", "gatal"}, {"ancient", "zustash"}, {"angelic", "sedil"}, {"angry", "ustos"}, {"armored", "tosid"}, {"artificial", "berim"}, {"ashen", "ibruk"}, {"autumnal", "thathil"}, {"awe-inspiring", "gostang"}, {"bad", "asdos"}, {"bald", "roder"}, {"big", "etag"}, {"black", "udir"}, {"blind", "nural"}, {"bloated", "okag"}, {"bloody", "nashon"}, {"blue", "enor"}, {"bold", "murak"}, {"bridled", "shalig"}, {"bright", "shin"}, {"brilliant", "akim"}, {"busy", "kitig"}, {"buttery", "reked"}, {"clear", "es"}, {"cold", "nekik"}, {"crazed", "uling"}, {"crazy", "dibesh"}, {"creamy", "berath"}, {"creppy", "innok"}, {"cross", "gesul"}, {"crystalline", "zas"}, {"dank", "unul"}, {"dark", "umom"}, {"dead", "nokor"}, {"dear", "asen"}, {"deep", "thol"}, {"domestic", "rodnul"}, {"doomed", "okbod"}, {"dutiful", "etest"}, {"east", "em"}, {"eerie", "rukal"}, {"elder", "okir"}, {"eternal", "zilir"}, {"everlasting", "issun"}, {"everseeing", "ilus"}, {"evil", "gedor"},
        {"false", "seth"}, {"fat", "er"}, {"fatal", "odroz"}, {"fetid", "lithrush"}, {"fierce", "zikel"}, {"fiery", "ziril"}, {"first", "uthar"}, {"fleshy", "ar"}, {"flowery", "totmon"}, {"foggy", "amug"}, {"foolish", "cabnul"}, {"fragile", "inglaz"}, {"free", "eshim"}, {"frilly", "thidas"}, {"fruity", "dozeb"}, {"garish", "shistat"}, {"gaunt", "zisur"}, {"geared", "olon"}, {"girdled", "gintar"}, {"gloved", "reg"}, {"godly", "nom"}, {"god-forsaken", "bumsoth"}, {"golden", "limul"}, {"grand", "zugob"}, {"great", "saram"}, {"green", "omer"}, {"grim", "usith"}, {"gristly", "mithmis"}, {"grizzly", "enol"}, {"hairy", "bistok"}, {"handy", "oddet"}, {"hateful", "lur"}, {"hellish", "shash"}, {"helmed", "zon"}, {"heroic", "obur"}, {"hideous", "lirlez"}, {"high", "erlin"}, {"hoary", "goster"}, {"holy", "kiron"}, {"hungry", "fokash"}, {"icy", "ushil"}, {"idle", "gumur"}, {"ull", "enen"}, {"impure", "goshist"}, {"inky", "likot"}, {"invisible", "nelzur"}, {"jaundiced", "bukshon"},
        {"just", "imketh"}, {"kind", "nosim"}, {"lacy", "vakist"}, {"lardy", "bul"}, {"larval", "onam"}, {"last", "ulol"}, {"lazy", "omoth"}, {"leafy", "govos"}, {"leaky", "orab"}, {"lean", "dalkem"}, {"legendary", "gomath"}, {"light", "istam"}, {"lone", "tetoth"}, {"long", "romek"}, {"lost", "uleng"}, {"lovely", "aval"}, {"low", "lushob"}, {"luris", "vurtib"}, {"lush", "lelgas"}, {"lustful", "nethgon"}, {"lyrical", "avan"}, {"magical", "aroth"}, {"mangy", "imust"}, {"mellow", "unob"}, {"mighty", "ekur"}, {"mindful", "uttan"}, {"misty", "sod"}, {"molten", "stesok"}, {"mousy", "stoling"}, {"muddy", "ol"}, {"musical", "shasad"}, {"mysterious", "shoveth"}, {"mythical", "lathon"}, {"nasty", "thubil"}, {"natural", "egom"}, {"negative", "ngutug"}, {"new", "ir"}, {"noble", "rithol"}, {"north", "irol"}, {"null", "rodim"}, {"oaken", "kin"}, {"oceanic", "migrur"}, {"old", "egar"}, {"padded", "dathnes"}, {"painful", "zulash"}, {"pale", "abal"}, {"peaceful", "bisol"}, {"poisoned", "inrus"},
        {"pregnant", "merir"}, {"prim", "enal"}, {"prime", "zeler"}, {"primitive", "stibbom"}, {"profane", "vildang"}, {"pulpy", "furgig"}, {"purple", "rushrul"}, {"putrid", "uvir"}, {"quick", "buket"}, {"rainy", "udar"}, {"random", "serkib"}, {"raw", "nar"}, {"red", "ang"}, {"regal", "nuden"}, {"ripe", "ethram"}, {"romantic", "abir"}, {"roomy", "omthel"}, {"rosy", "istbar"}, {"rough", "dumat"}, {"royal", "relon"}, {"ruined", "notlith"}, {"rumored", "tithleth"}, {"salty", "nabid"}, {"satiny", "gasis"}, {"savage", "noglesh"}, {"scabrous", "nanul"}, {"secretive", "nekut"}, {"sick", "kafash"}, {"silent", "eshom"}, {"silken", "nesteth"}, {"silky", "thebil"}, {"silty", "ammesh"}, {"silvery", "ral"}, {"sinful", "reksas"}, {"slim", "gansit"}, {"slitted", "sakil"}, {"smooth", "umar"}, {"sooty", "bonun"}, {"south", "lal"}, {"spicy", "omat"}, {"spidery", "soshor"}, {"spry", "ves"}, {"stern", "ginon"}, {"sticky", "metin"}, {"stormy", "togal"}, {"strange", "mot"}, {"strapping", "nefast"},
        {"strong", "emen"}, {"stunted", "ibas"}, {"stupid", "othob"}, {"subordinate", "idgag"}, {"sugary", "ibes"}, {"sullen", "akuth"}, {"sunny", "ad"}, {"sweet", "tecak"}, {"swift", "subet"}, {"terrible", "angzak"}, {"tight", "lid"}, {"touchy", "stivut"}, {"trim", "dizesh"}, {"ugly", "eknar"}, {"ultimate", "isrir"}, {"unbridled", "ticek"}, {"ungodly", "othash"}, {"unholy", "kokdath"}, {"unkempt", "distat"}, {"unseen", "nirur"}, {"untoward", "kiret"}, {"unwelcome", "thisrid"}, {"useless", "kizab"}, {"velvety", "mirstal"}, {"vile", "munsog"}, {"violent", "liruk"}, {"violet", "geget"}, {"watchful", "isden"}, {"wavy", "kussad"}, {"west", "sital"}, {"white", "volal"}, {"wicked", "lish"}, {"wild", "unrist"}, {"willful", "ud"}, {"wispy", "lim"}, {"wondrous", "anur"}, {"wooden", "lolum"}, {"wretched", "lerush"}, {"yellow", "inol"}, {"young", "ging"}, {"youthful", "rilem"}, {"earthen", "ber"}, {"common", "ulter"}, {"diamond", "doren"}, {"dreamy", "nazom"}, {"tin", "akrul"},
        {"copper", "gusil"}, {"bronze", "kilrud"}, {"grantie", "lolok"}, {"fancy", "lemlor"}, {"frothy", "gulgum"}, {"glacial", "usir"}, {"jade", "otil"}, {"ivory", "sosad"}, {"limp", "dithbish"}, {"lucid", "ekir"}, {"mountainous", "onol"}, {"mucous", "godum"}, {"patterned", "lilar"}, {"plain", "bimmon"}, {"pointy", "akil"}, {"speckled", "kik"}, {"wealthy", "limar"}, {"shimsical", "ken"}, {"whirling", "estil"}, {"livid", "azzin"}, {"tepid", "selen"}, {"honest", "gadan"}, {"imperial", "thalal"}, {"simple", "guz"}, {"crimson", "thestar"}, {"subtle", "ozor"}, {"amazing", "edos"}, {"alchemical", "anzish"}, {"insightful", "luk"}, {"persuasive", "eges"}, {"basic", "enseb"}, {"systemic", "idith"}, {"clean", "lecad"}, {"glorious", "anil"}, {"dismal", "nobang"}, {"radiant", "atesh"}, {"messianic", "milol"}, {"laborious", "erith"}, {"chunky", "bor"}, {"slippery", "foker"}, {"single", "elik"}, {"permanent", "irlom"}, {"responsible", "stemel"}, {"constructive", "aban"}, {"gross", "tholthod"},
        {"gnarled", "lobor"}, {"naughty", "kednath"}, {"playful", "titthal"}, {"flimsy", "tetist"}, {"greater", "riras"}, {"greatest", "toras"}, {"lesser", "gekur"}, {"least", "gudos"}, {"bearded", "durad"}, {"dreadful", "zevut"}, {"walled", "adil"}, {"fragrant", "shosel"}, {"lined", "vel"}, {"waxy", "rithlut"}, {"glittery", "eser"}, {"hollow", "ugosh"}, {"full", "esmul"}, {"empty", "kisat"}, {"wordy", "il"}, {"intense", "rinul"}, {"sad", "mukar"}, {"glad", "amkin"}, {"tragic", "mosos"}, {"ponderous", "umshad"}, {"heavenly", "dasel"}, {"round", "lames"}, {"rounded", "lavath"}, {"unspeakable", "ozur"}, {"unthinkable", "zotthol"}, {"unnameable", "nan"}, {"calamitous", "rorash"}, {"cyclopean", "nguteg"}, {"tame", "osust"}, {"untamed", "umam"}, {"trite", "ebbus"}, {"trifling", "bobet"}, {"rank", "ong"}, {"rancorous", "zokgen"}, {"bitter", "raduk"}, {"sour", "zunek"}, {"dangerous", "kezat"}, {"impervious", "kadan"}, {"unswerving", "sar"}, {"luxurious", "ertal"}, {"euphoric", "ramol"},
        {"scintillating", "girust"}, {"divine", "nabas"}, {"tainted", "ongos"}, {"corrupt", "shusug"}, {"maligned", "tongus"}, {"malign", "tustzal"}, {"malignant", "kugneb"}, {"trustworthy", "arin"}, {"untrustworthy", "govul"}, {"dishonest", "vetor"}, {"blighted", "sharsid"}, {"cunning", "nakis"}, {"sly", "lanir"}, {"rustic", "ikul"}, {"homely", "nakbab"}, {"lonely", "nimem"}, {"lonesome", "numol"}, {"closed", "urol"}, {"wayward", "onul"}, {"monstrous", "ushang"}, {"sensitive", "emal"}, {"insensitive", "ethzuth"}, {"sensual", "gathil"}, {"odorous", "kebon"}, {"malodorous", "sutung"}, {"ignorant", "nizdast"}, {"ignoble", "mimkot"}, {"humble", "vir"}, {"moral", "tumam"}, {"immoral", "osstam"}, {"superior", "kulsim"}, {"inferior", "gemis"}, {"infinite", "er"}, {"sable", "fenok"}, {"fell", "igrish"}, {"dignified", "zengod"}, {"undignified", "ister"}, {"righteous", "kirar"}, {"absolute", "ilas"}, {"fair", "anuz"}, {"fair", "angen"}, {"snarling", "desis"}, {"loyal", "damel"},
        {"disloyal", "assog"}, {"helpful", "usen"}, {"friendly", "babin"}, {"courteous", "tustem"}, {"cheerful", "debben"}, {"thrifty", "kabat"}, {"brave", "atast"}, {"revered", "ebal"}, {"venerable", "lanzil"}, {"national", "solam"}, {"considerate", "nucam"}, {"inconsiderate", "mengthul"}, {"inconvenient", "themnol"}, {"flighty", "rersir"}, {"gilded", "oltar"}, {"plaited", "mamot"}, {"braided", "nakuth"}, {"pleated", "udist"}, {"folded", "ost"}, {"uncommon", "morus"}, {"rare", "akrel"}, {"scarce", "kith"}, {"remarkable", "bomel"}, {"unremarkable", "orngim"}, {"solitary", "ngubmul"}, {"bent", "mat"}, {"blameless", "ustan"}, {"trussed", "tilesh"}, {"skewered", "gecast"}, {"scultped", "aran"}, {"tressed", "stelmith"}, {"curled", "amem"}, {"tufted", "kasben"}, {"mean", "fashuk"}, {"mean", "ubom"}, {"shameful", "mostod"}, {"ashamed", "mangrod"}, {"steamy", "keng"}, {"worried", "bumal"}, {"blanketed", "lal"}, {"cloudy", "lun"}, {"plated", "kugik"}, {"sorcerous", "olthez"},
        {"bewitched", "nonshut"}, {"enchanted", "minbaz"}, {"stinky", "rithog"}, {"windy", "num"}, {"hazy", "mis"}, {"torturous", "mugshith"}, {"scholarly", "mishthem"}, {"massive", "zansong"}, {"large", "or"}, {"small", "est"}, {"tiled", "bot"}, {"stale", "vuzded"}, {"fresh", "emet"}, {"worthy", "duthal"}, {"worthless", "cugshil"}, {"frightful", "shasar"}, {"revolting", "emdush"}, {"disgusting", "shungmag"}, {"outrageous", "zar"}, {"cruel", "luror"}, {"deviant", "manthul"}, {"devious", "sholkik"}, {"fabulous", "sankest"}, {"skinny", "afen"}, {"narrow", "dast"}, {"grieving", "nothis"}, {"belted", "imaz"}, {"sandaled", "sosh"}, {"future", "zalud"}, {"past", "geth"}, {"present", "udiz"}, {"split", "ziksis"}, {"brash", "midrim"}, {"brazen", "urthaz"}, {"strangled", "vuknud"}, {"muscular", "thum"}, {"dim", "arosh"}, {"spurting", "githstak"}, {"risky", "neshast"}, {"mirthful", "legan"}, {"gleeful", "alil"}, {"drab", "bibar"}, {"oracular", "som"}, {"decisive", "sestan"},
        {"special", "ganad"}, {"portentious", "niral"}, {"momentous", "zavaz"}, {"infallible", "tellist"}, {"ambiguous", "umgan"}, {"curious", "kesham"}, {"obscure", "azmol"}, {"obscene", "thokdeg"}, {"vulgar", "detgash"}, {"ominous", "zocuk"}, {"occult", "asrath"}, {"ordered", "shed"}, {"faithful", "tabar"}, {"guilty", "lushut"}, {"girlish", "saruth"}, {"boyish", "arged"}, {"slick", "kud"}, {"still", "isan"}, {"calm", "betan"}, {"laconic", "elol"}, {"mute", "rul"}, {"noiseless", "zaled"}, {"quiescent", "esar"}, {"quiet", "kas"}, {"reticent", "zizcum"}, {"saturnine", "vathem"}, {"speechless", "mishak"}, {"taciturn", "dubmen"}, {"fortunate", "akam"}, {"accidental", "kithdeng"}, {"circumstantial", "assar"}, {"contingent", "mingtuth"}, {"coicnidential", "rafum"}, {"lucky", "merseth"}, {"certain", "os"}, {"uncertain", "itnet"}, {"fortuitous", "gisstir"}, {"incidental", "dalem"}, {"amusing", "idath"}, {"distracting", "ashzos"}, {"competitive", "agoth"}, {"contested", "agesh"},
        {"matched", "dalzat"}, {"matched", "tad"}, {"strategic", "arceth"}, {"tactical", "rimad"}, {"autonomous", "shigin"}, {"emancipated", "kastol"}, {"released", "sobir"}, {"relieved", "noram"}, {"even", "deg"}, {"balanced", "neth"}, {"equivalent", "maskir"}, {"static", "shagog"}, {"symmetric", "shazak"}, {"equal", "tinoth"}, {"harmonious", "thir"}, {"neutral", "ital"}, {"stable", "nulral"}, {"dour", "gomom"}, {"severe", "borlon"}, {"glum", "ngobol"}, {"hot", "vush"}, {"cavernous", "kor"}, {"shady", "ashmon"}, {"veiled", "bisek"}, {"umbral", "gosmer"}, {"murky", "bothon"}, {"faint", "losis"}, {"somber", "azuz"}, {"tenebrous", "golast"}, {"morose", "ednad"}, {"beloved", "arom"}, {"escorted", "ninur"}, {"pungent", "fongbez"}, {"musty", "arrug"}, {"infected", "avush"}, {"afflicted", "thokit"}, {"aching", "agseth"}, {"epidemic", "sharast"}, {"yawning", "am"}, {"assaulted", "arist"}, {"carnal", "sheced"}, {"strifeful", "stin"}, {"safe", "ekast"}, {"flayed", "gongash"}, {"oily", "uzol"},
        {"suicidal", "moshnum"}, {"tempted", "becor"}, {"contemptible", "gishgil"}, {"sacrificial", "metom"}, {"trampled", "tangath"}, {"malicious", "ezost"}, {"spiteful", "zakgol"}, {"coastal", "teling"}, {"brutal", "tirdug"}, {"harsh", "gethust"}, {"pristine", "maram"}, {"ferocious", "nidost"}, {"barbarous", "bashnom"}, {"feral", "ekzong"}, {"furious", "thusest"}, {"ruthless", "bocash"}, {"gory", "dedros"}, {"virtuous", "icum"}, {"scandalous", "etvuth"}, {"climactic", "lir"}, {"crested", "zim"}, {"most", "tel"}, {"blunt", "unal"}, {"frosty", "nisgak"}, {"feverish", "dotir"}, {"humid", "kalreth"}, {"humorous", "alek"}, {"comedic", "resil"}, {"sizzling", "umstiz"}, {"sweltering", "keshshak"}, {"warm", "sirab"}, {"torrid", "shaketh"}, {"acrid", "tatek"}, {"craterous", "sulus"}, {"dented", "geb"}, {"depressed", "ozon"}, {"dimpled", "storlut"}, {"dipped", "bekar"}, {"excavated", "zamnuth"}, {"grooved", "edtul"}, {"distant", "ruthosh"}, {"notched", "lisat"}, {"sagging", "zagug"},
        {"socketed", "sesh"}, {"fenced", "ustuth"}, {"barricaded", "tholtig"}, {"blockaded", "medtob"}, {"defended", "nadak"}, {"defensive", "nirmek"}, {"abyssal", "ngalak"}, {"abysmal", "sosas"}, {"submerged", "rul"}, {"hale", "vosut"}, {"robust", "subil"}, {"hardy", "ifin"}, {"vigorous", "okosh"}, {"dabbling", "gikut"}, {"doused", "rem"}, {"drenched", "thiktog"}, {"moist", "idash"}, {"sloppy", "lirer"}, {"soaked", "adag"}, {"spattered", "isak"}, {"sprayed", "basen"}, {"spread", "koman"}, {"twinkling", "shetbeth"}, {"wet", "kathil"}, {"faded", "undin"}, {"colorless", "mekur"}, {"dull", "rumad"}, {"evaporated", "esast"}, {"lustrous", "suvas"}, {"vanished", "oshot"}, {"washed", "stelid"}, {"abated", "med"}, {"declining", "inir"}, {"deteriorated", "sibosh"}, {"diminished", "lunrud"}, {"dispersed", "olum"}, {"droopy", "shuk"}, {"dwindling", "oler"}, {"kindled", "stizash"}, {"stoked", "gusgash"}, {"stirred", "edan"}, {"fed", "ked"}, {"failed", "ungeg"}, {"languishing", "merrang"},
        {"lessened", "gudid"}, {"shriveled", "istik"}, {"sunken", "akmam"}, {"tapered", "timnar"}, {"thin", "elis"}, {"tired", "kan"}, {"waning", "lelum"}, {"weak", "othil"}, {"wilted", "othos"}, {"wilthered", "nentuk"}, {"honorable", "dural"}, {"adorable", "salir"}, {"celebrated", "fazis"}, {"confident", "thiken"}, {"deferent", "ulmush"}, {"distinct", "tastrod"}, {"elevated", "todor"}, {"esteemed", "ostath"}, {"exalted", "thasdoth"}, {"famous", "belal"}, {"mortal", "tunom"}, {"immortal", "kudar"}, {"lauded", "gebar"}, {"obeisant", "nothlok"}, {"praised", "libad"}, {"prestigious", "demur"}, {"renowned", "elbel"}, {"reputed", "ennol"}, {"worshipful", "soloz"}, {"chaste", "musod"}, {"courageous", "samam"}, {"decent", "ethad"}, {"good", "eshon"}, {"innocent", "etom"}, {"modest", "ernam"}, {"pure", "enam"}, {"true", "atol"}, {"truthful", "osir"}, {"virginal", "vathez"}, {"held", "kegeth"}, {"scalded", "cudist"}, {"scaly", "katak"}, {"labyrinthine", " lumnum"}, {"crowded", "thad"},
        {"familial", "shan"}, {"organized", "stegeth"}, {"tangled", "lerteth"}, {"entangled", "stistmig"}, {"puzzling", "luslen"}, {"perplexing", "sherik"}, {"combined", "artob"}, {"flickering", "nelas"}, {"branded", "zes"}, {"singed", "necik"}, {"searing", "uthir"}, {"scorching", "othlest"}, {"roasted", "ibesh"}, {"parched", "fash"}, {"ignited", "anist"}, {"incinerated", "ordir"}, {"slowing", "rab"}, {"cremated", "orshet"}, {"factional", "uzlir"}, {"crewed", "ginet"}, {"cooperative", "etnar"}, {"routed", "muzir"}, {"scraped", "igath"}, {"scoured", "bubnus"}, {"scrubbed", "ithod"}, {"shaken", "uthmik"}, {"soapy", "uben"}, {"spongy", "adbok"}, {"whiskered", "rikkir"}, {"dominant", "akest"}, {"grasping", "gidthur"}, {"influential", "immast"}, {"tenacious", "vudnis"}, {"confining", "kacoth"}, {"contained", "etost"}, {"cradled", "arban"}, {"embraced", "kurol"}, {"circular", "oshur"}, {"square", "vathsith"}, {"triangular", "bithsest"}, {"connected", "kekzig"}, {"merged", "kir"},
        {"confusing", "shadmal"}, {"complex", "adol"}, {"meandering", "ablish"}, {"muddled", "shislug"}, {"bewildering", "zutshosh"}, {"problematic", "batok"}, {"intricate", "izkil"}, {"polished", "deleth"}, {"purged", "thetust"}, {"banded", "emath"}, {"tall", "shukar"}, {"short", "idrom"}, {"bulbous", "gubel"}, {"allied", "astel"}, {"enjoyable", "nakas"}, {"fondled", "gatiz"}, {"imprisoned", "ushesh"}, {"nourishing", "katthir"}, {"squeezing", "ikthag"}, {"defective", "aluth"}, {"perfect", "ator"}, {"bejeweled", "istrath"}, {"blotted", "kod"}, {"blowing", "etes"}, {"brushed", "nosing"}, {"erased", "othor"}, {"tender", "ittas"}, {"mechanical", "bembul"}, {"smeared", "duz"}, {"tattooed", "zeg"}, {"weathered", "edol"}, {"entrancing", "desor"}, {"delightful", "amith"}, {"joyous", "ilir"}, {"frigid", "ishol"}, {"passionate", "ishen"}, {"ardent", "kiddir"}, {"boring", "edod"}, {"flecked", "astan"}, {"spotted", "tangak"}, {"creative", "dobar"}, {"poetic", "dimshas"}, {"hermetic", "oshosh"},
        {"reclusive", "orstist"}, {"named", "kab"}, {"rhyming", "nanir"}, {"rhythmic", "irid"}, {"squashed", "stukon"}, {"habitual", "oruk"}, {"disemboweled", "gorroth"}, {"eviscerated", "egstak"}, {"rapid", "asas"}, {"healing", "ikal"}, {"slow", "dezrem"}, {"mired", "sebshos"}, {"admired", "nebel"}, {"lamented", "ralath"}, {"adventurous", "cenath"}, {"mournful", "leshal"}, {"anguished", "roldeth"}, {"taut", "ugut"}, {"deified", "arbost"}, {"infamous", "sedish"}, {"mortified", "osresh"}, {"riddled", "dallith"}, {"amber", "thukkan"}, {"amethyst", "alron"}, {"aqua", "ungob"}, {"aquamarine", "utost"}, {"gray", "bel"}, {"auburn", "sanus"}, {"azure", "kithal"}, {"beige", "theb"}, {"brass", "konos"}, {"brown", "neb"}, {"buff", "itred"}, {"sienna", "ecosh"}, {"umber", "cegol"}, {"cardinal", "luthoz"}, {"carmine", "thastith"}, {"cerulean", "remang"}, {"charcoal", "athser"}, {"chartreuse", "ngusham"}, {"chestnut", "gingik"}, {"chocolate", "rangab"}, {"cinnamon", "kontuth"},
        {"cobalt", "letmos"}, {"indigo", "mishim"}, {"olive", "losush"}, {"pink", "othbem"}, {"scarlet", "bengeg"}, {"tan", "lasgan"}, {"ecru", "utal"}, {"emerald", "sedur"}, {"flaxen", "engig"}, {"fushia", "sunggor"}, {"goldenrod", "thistun"}, {"heliotrope", "koshdes"}, {"lavender", "ngefel"}, {"mahogany", "sezom"}, {"maroon", "shashdon"}, {"mauve", "mebnith"}, {"taupe", "kan"}, {"mint", "gitnuk"}, {"ochre", "nokim"}, {"puce", "bidnoz"}, {"russet", "oten"}, {"saffron", "ushdish"}, {"sepia", "kitung"}, {"teal", "nubam"}, {"turquoise", "onget"}, {"vermilion", "dengstam"}, {"fated", "tarem"}, {"destined", "nam"}, {"little", "tokmek"}, {"early", "ed"}, {"late", "et"}, {"living", "thunen"}, {"hopeful", "zanos"}, {"beautiful", "kinem"}, {"respectful", "rirnol"}, {"heavy", "danman"}, {"born", "noton"}, {"learned", "turel"}, {"mischevious", "cemosh"}, {"wise", "dosim"}, {"knowing", "musar"}, {"cracked", "obot"}, {"shattered", "baktus"}, {"squat", "tumos"}, {"festive", "korsid"}};

        public static string[,] theXs = {{"abbey", "kulet"}, {"ace", "alak"}, {"act", "bidok"}, {"age", "anam"}, {"ages", "anam"}, {"ale", "mabdug"}, {"ales", "mabdug"}, {"ancient", "zustash"}, {"angel", "sedil"}, {"anger", "ustos"}, {"animal", "emar"}, {"ape", "izeg"}, {"apes", "izeg"}, {"apple", "bemong"}, {"apples", "bemong"}, {"arm", "ontak"}, {"armor", "tosid"}, {"armors", "tosid"}, {"arrow", "feb"}, {"artifice", "berim"}, {"artifices", "berim"}, {"ash", "ibruk"}, {"aunt", "ermis"}, {"aunt", "ermis"}, {"aura", "thoth"}, {"auras", "thoth"}, {"autumn", "thatthil"}, {"axe", "libash"}, {"baldness", "roder"}, {"baker", "nel"}, {"ball", "biban"}, {"balls", "biban"}, {"bar", "ish"}, {"bars", "ish"}, {"barb", "robek"}, {"barbs", "robek"}, {"bath", "olmul"}, {"battle", "nokzam"}, {"battles", "nokzam"}, {"beak", "umuth"}, {"beast", "fer"}, {"bear", "uvel"}, {"bee", "agek"}, {"bees", "agek"}, {"beer", "ucat"}, {"beers", "ucat"}, {"beetle", "ngarak"}, {"beetles", "ngarak"}, {"beguiler", "enir"}, {"belch", "ugath"},
        {"belches", "ugath"}, {"berry", "lisig"}, {"berries", "lisig"}, {"bile", "erong"}, {"biles", "erong"}, {"bin", "osed"}, {"bins", "osed"}, {"bird", "lalnar"}, {"birds", "lanlar"}, {"blade", "tarmid"}, {"blades", "tarmid"}, {"blaze", "sakrith"}, {"blazes", "sakrith"}, {"blister", "bugsud"}, {"blisters", "bugsud"}, {"bloat", "okag"}, {"blood", "nazush"}, {"blossom", "atrid"}, {"boar", "dustik"}, {"boat", "kogan"}, {"boats", "kogan"}, {"bodice", "ingish"}, {"bodices", "ingish"}, {"bog", "dudgoth"}, {"boil", "stalkob"}, {"boils", "stalkob"}, {"bolt", "alath"}, {"bolts", "alath"}, {"bone", "osod"}, {"bones", "osod"}, {"book", "thikut"}, {"books", "thikut"}, {"boot", "cog"}, {"boots", "cog"}, {"bow", "egdoth"}, {"bows", "egdoth"}, {"brain", "idek"}, {"brains", "idek"}, {"breach", "ust"}, {"breeches", "suthmam"}, {"bread", "im"}, {"breaker", "okab"}, {"breakfast", "onlil"}, {"breakfasts", "onlil"}, {"breath", "gasol"}, {"breed", "tegir"}, {"brew", "namash"}, {"bridge", "noval"},
        {"bridle", "shalig"}, {"brightness", "shin"}, {"brightnesses", "shin"}, {"bristle", "lek"}, {"bristles", "lek"}, {"brilliance", "akim"}, {"brilliances", "akim"}, {"brim", "kakdal"}, {"brother", "alud"}, {"brunch", "olom"}, {"buck", "elot"}, {"buckle", "rozsed"}, {"buckles", "rozsed"}, {"bunch", "thos"}, {"bunches", "thos"}, {"burden", "okon"}, {"burdens", "okons"}, {"burn", "ning"}, {"burns", "ning"}, {"burial", "ostar"}, {"bush", "rorul"}, {"bushes", "rorul"}, {"bushel", "kovath"}, {"bushels", "kovath"}, {"bust", "ablel"}, {"buster", "stal"}, {"business", "girtol"}, {"businesses", "girtol"}, {"business", "kitig"}, {"business", "kitig"}, {"butcher", "lokast"}, {"butter", "reked"}, {"butters", "reked"}, {"butterfly", "comnith"}, {"button", "sidos"}, {"buttons", "sidos"}, {"buzzard", "setnek"}, {"cad", "nug"}, {"cage", "mokez"}, {"cake", "cos"}, {"cakes", "cos"}, {"call", "idos"}, {"camp", "ogik"}, {"camps", "ogik"}, {"cancer", "utheg"}, {"candle", "tilgil"},
        {"candles", "tilgil"}, {"candy", "ebsas"}, {"candies", "ebsas"}, {"canker", "lurak"}, {"canyon", "tobul"}, {"canyon", "tobul"}, {"carnage", "ilush"}, {"casket", "denush"}, {"castle", "rimtar"}, {"cat", "kun"}, {"cave", "as"}, {"cell", "kiror"}, {"chain", "nicat"}, {"chains", "nicat"}, {"chant", "onshen"}, {"chants", "onshen"}, {"chaos", "rerith"}, {"chamber", "mafol"}, {"chambers", "mafol"}, {"charm", "itdun"}, {"charms", "itdun"}, {"child", "tilat"}, {"chill", "itat"}, {"chills", "itat"}, {"chip", "egot"}, {"chips", "egot"}, {"cinder", "sudir"}, {"cinders", "sudir"}, {"clam", "odshith"}, {"clasp", "dodok"}, {"clasps", "dodok"}, {"claw", "sinsot"}, {"claws", "consot"}, {"clearing", "dostob"}, {"clearings", "dostob"}, {"cleft", "gast"}, {"cloak", "romlam"}, {"clock", "daral"}, {"clocks", "daral"}, {"clod", "an"}, {"clods", "an"}, {"cloister", "oddom"}, {"cloisters", "oddom"}, {"closet", "zagel"}, {"closets", "zagel"}, {"club", "og"}, {"cluster", "shatag"},
        {"clusters", "shatag"}, {"clutter", "om"}, {"clutter", "om"}, {"cobra", "gisek"}, {"coil", "balad"}, {"coils", "balad"}, {"color", "dakas"}, {"colors", "dakas"}, {"comet", "colek"}, {"conqueror", "sog"}, {"cook", "rafar"}, {"cover", "laltur"}, {"covers", "laltur"}, {"cotton", "ikeng"}, {"couple", "dan"}, {"crab", "ozsit"}, {"cream", "berath"}, {"creams", "berath"}, {"creek", "zangin"}, {"creep", "shadkik"}, {"crescent", "vukcas"}, {"cross", "metul"}, {"crosses", "metul"}, {"crow", "ustir"}, {"crown", "torish"}, {"crucifixion", "memrut"}, {"crusher", "angrir"}, {"crypt", "momuz"}, {"crypt", "momuz"}, {"crystal", "zas"}, {"cudgel", "astesh"}, {"cup", "ofid"}, {"curse", "mothram"}, {"curses", "mothram"}, {"cut", "rit"}, {"cuts", "rit"}, {"cyst", "nolthag"}, {"cysts", "molthag"}, {"dance", "matul"}, {"dagger", "urist"}, {"daggers", "urists"}, {"date", "dem"}, {"dates", "dem"}, {"dawn", "kodor"}, {"day", "alod"}, {"days", "alod"}, {"dead", "nokor"}, {"death", "rash"},
        {"decay", "ursas"}, {"deceiver", "vakun"}, {"deep", "thol"}, {"deeps", "thol"}, {"deer", "kizbiz"}, {"deer", "kizbiz"}, {"demon", "uthgir"}, {"despair", "onor"}, {"destroyer", "gar"}, {"destruction", "terstum"}, {"devil", "zagith"}, {"devourer", "noshtath"}, {"dinner", "uk"}, {"dinners", "uk"}, {"dirt", "amur"}, {"ditch", "minran"}, {"dog", "idar"}, {"domicile", "rodnul"}, {"domiciles", "rodnul"}, {"doom", "okbod"}, {"door", "tun"}, {"doors", "tun"}, {"dragon", "mamgoz"}, {"drain", "fak"}, {"drawl", "ogon"}, {"drawls", "ogon"}, {"dreg", "remrit"}, {"dregs", "remrit"}, {"dress", "dresses"}, {"drinker", "kosak"}, {"drip", "sub"}, {"drips", "sub"}, {"drool", "shegum"}, {"drum", "talin"}, {"drums", "talin"}, {"dump", "ammeb"}, {"dumps", "ammeb"}, {"dumpling", "sakub"}, {"dumplings", "sakub"}, {"dung", "tig"}, {"dungs", "tig"}, {"dungeon", "edir"}, {"dungeon", "edir"}, {"dusk", "tath"}, {"dust", "vesh"}, {"dusts", "vesh"}, {"duty", "etest"}, {"duties", "etest"}, {"dye", "atir"},
        {"dyes", "atir"}, {"eagle", "lorsith"}, {"eagles", "lorsith"}, {"ear", "rir"}, {"ears", "rir"}, {"eater", "deb"}, {"eel", "eshgor"}, {"eels", "eshgor"}, {"egg", "acob"}, {"eggs", "acob"}, {"elder", "okir"}, {"entrails", "arngish"}, {"evil", "gedor"}, {"evils", "gedor"}, {"execution", "ramtak"}, {"executions", "ramtak"}, {"executioner", "sombith"}, {"eye", "ker"}, {"eyes", "ker"}, {"face", "linem"}, {"faces", "linem"}, {"fall", "umid"}, {"famine", "sogdol"}, {"famines", "sogdol"}, {"fang", "shis"}, {"fangs", "shis"}, {"fat", "er"}, {"fats", "er"}, {"father", "urem"}, {"fear", "nist"}, {"fears", "nist"}, {"feast", "odad"}, {"feasts", "odad"}, {"fiend", "zotir"}, {"filth", "zikath"}, {"filths", "zikath"}, {"fin", "stagshil"}, {"fins", "stagshil"}, {"finder", "atol"}, {"finger", "ok"}, {"fingers", "ok"}, {"fire", "ziril"}, {"fires", "ziril"}, {"fish", "tatlosh"}, {"fisher", "ngitkar"}, {"fist", "dur"}, {"fists", "dur"}, {"flame", "keshan"}, {"flames", "keshan"}, {"flank", "ned"},
        {"flanks", "ned"}, {"flea", "eststek"}, {"fleas", "eststek"}, {"flesh", "ar"}, {"flood", "laluth"}, {"flower", "totmon"}, {"flute", "bem"}, {"flutes", "bem"}, {"fly", "fenglel"}, {"flies", "fenglel"}, {"flier", "gigin"}, {"focus", "atham"}, {"fog", "amug"}, {"fogs", "smug"}, {"fool", "cabnul"}, {"foot", "nog"}, {"feet", "nog"}, {"forest", "fotthor"}, {"forests", "fotthor"}, {"fork", "iltang"}, {"forks", "iltang"}, {"fortification", "dumed"}, {"fortress", "geshud"}, {"fragment", "ezneth"}, {"fragments", "ezneth"}, {"frame", "toklom"}, {"frames", "tiklom"}, {"frenzy", "lumash"}, {"frill", "thidas"}, {"frills", "thidas"}, {"frog", "enog"}, {"fruit", "dozeb"}, {"fruits", "dozeb"}, {"fungus", "muz"}, {"fungi", "muz"}, {"fur", "ast"}, {"furs", "ast"}, {"gall", "dushig"}, {"galls", "dushig"}, {"game", "bakat"}, {"games", "bakat"}, {"garlic", "goral"}, {"garnish", "kenmak"}, {"garnishes", "kebmak"}, {"gate", "inod"}, {"gates", "inod"}, {"gaze", "list"}, {"gear", "olon"},
        {"gears", "olon"}, {"gerbil", "ertong"}, {"ghost", "ngotol"}, {"ghoul", "kolad"}, {"gift", "egen"}, {"gifts", "egen"}, {"gill", "rubal"}, {"gills", "rubal"}, {"girdle", "gintar"}, {"girdles", "gintar"}, {"gland", "figul"}, {"glands", "figul"}, {"glaze", "fikod"}, {"glazes", "fikod"}, {"glen", "bebmal"}, {"glens", "bebmal"}, {"glimmer", "katdir"}, {"gloss", "igest"}, {"glosses", "igest"}, {"glove", "reg"}, {"gloves", "reg"}, {"glutton", "ubur"}, {"goat", "belbez"}, {"god", "nom"}, {"gold", " limul"}, {"goose", "kurig"}, {"geese", "kurig"}, {"gorge", "erib"}, {"grain", "mas"}, {"grains", "mas"}, {"grape", "mashas"}, {"grape", "mashas"}, {"grass", "isin"}, {"grasses", "isin"}, {"grave", "mondul"}, {"grease", "emsiz"}, {"greed", "dal"}, {"griffon", "sumin"}, {"griffons", "sumun"}, {"grip", "zagod"}, {"grip", "zagod"}, {"gristle", "mothmis"}, {"grizzle", "enol"}, {"grove", "munest"}, {"grower", "bol"}, {"growl", "uz"}, {"growls", "uz"}, {"growth", "bal"}, {"growths", "bal"},
        {"grub", "sitheb"}, {"grubs", "sitheb"}, {"guard", "dithnur"}, {"guile", "ilbad"}, {"guiles", "ilbad"}, {"guise", "rurast"}, {"guises", "rurast"}, {"gut", "suton"}, {"guts", "suton"}, {"gutter", "nuglush"}, {"gutters", "nuglush"}, {"hag", "ulthush"}, {"hair", "razes"}, {"hairs", "razes"}, {"hame", "ezum"}, {"hames", "ezum"}, {"hammer", "nil"}, {"hammers", "nil"}, {"hammerer", "unil"}, {"hand", "otad"}, {"hands", "otad"}, {"hare", "thetdel"}, {"hares", "thetdul"}, {"harvest", "golus"}, {"harvests", "golud"}, {"harvester", "ud"}, {"hatchet", "kadol"}, {"hatchets", "kadol"}, {"hate", "lur"}, {"haunt", "dumur"}, {"haunts", "dumur"}, {"hawk", "aknun"}, {"hay", "otel"}, {"hays", "otel"}, {"head", "ser"}, {"heart", "zanor"}, {"hearth", "ur"}, {"heather", "bokbon"}, {"heathers", "bokbon"}, {"hedge", "efim"}, {"hedges", "efim"}, {"hell", "shash"}, {"helm", "zon"}, {"helms", "zon"}, {"hero", "obur"}, {"hex", "banik"}, {"hide", "sebir"}, {"hides", "sebir"}, {"hill", "inen"},
        {"hills", "inen"}, {"hip", "amat"}, {"hips", "amat"}, {"hog", "tarag"}, {"holiness", "kiron"}, {"hole", "oggez"}, {"holes", "oggez"}, {"home", "bom"}, {"homes", "bom"}, {"honey", "stetar"}, {"honeys", "stetar"}, {"hood", "sikel"}, {"hoof", "unnos"}, {"hooves", "unnos"}, {"hop", "kisul"}, {"hopper", "ikus"}, {"horn", "sheget"}, {"horns", "sheget"}, {"horse", "famthut"}, {"horses", "famthut"}, {"hound", "rorung"}, {"hounds", "rorung"}, {"howl", "idor"}, {"howl", "idor"}, {"hug", "enur"}, {"hugs", "enur"}, {"hunger", "fokash"}, {"ice", "ushil"}, {"idleness", "gumur"}, {"idol", "ular"}, {"illness", "enen"}, {"illnesses", "enen"}, {"incense", "azkob"}, {"incenses", "azkob"}, {"inch", "meb"}, {"inches", "meb"}, {"ink", "likot"}, {"inks", "likot"}, {"inn", "stetnin"}, {"insanity", "zarut"}, {"insanities", "zarut"}, {"iron", "datan"}, {"irons", "datan"}, {"itch", "tabmik"}, {"itches", "tabmik"}, {"ivy", "rinal"}, {"jack", "ebgok"}, {"jackal", "soshosh"}, {"jaundice", "bukshon"},
        {"jaw", "stigil"}, {"jaws", "stigil"}, {"jester", "lumen"}, {"jesters", "lumen"}, {"joke", "maton"}, {"jokes", "maton"}, {"juggler", "abol"}, {"juice", "cim"}, {"juices", "cim"}, {"jungle", "egath"}, {"jungles", "egath"}, {"justice", "imketh"}, {"keeper", "zuden"}, {"keg", "emtan"}, {"kegs", "emtan"}, {"key", "edem"}, {"keys", "edem"}, {"kindness", "nosim"}, {"kindnesses", "nosim"}, {"killer", "vagush"}, {"kiss", "alis"}, {"kisses", "alis"}, {"king", "etar"}, {"knife", "zasit"}, {"knives", "zasit"}, {"knight", "arzes"}, {"knot", "oth"}, {"knots", "osh"}, {"lace", "vakist"}, {"laces", "vakist"}, {"lake", "ner"}, {"lakes", "ner"}, {"lard", "bul"}, {"lark", "iddor"}, {"larks", "iddor"}, {"larva", "onam"}, {"law", "toral"}, {"laws", "toral"}, {"laziness", "omoth"}, {"leader", "erar"}, {"leaf", "govos"}, {"leaves", "govos"}, {"leak", "orab"}, {"leaks", "orab"}, {"leech", "subol"}, {"leeches", "subol"}, {"legend", "gomath"}, {"lens", "cerol"}, {"lenses", "cerol"},
        {"leopard", "mingkil"}, {"leper", "detthost"}, {"leprosy", "rerik"}, {"letter", "lolor"}, {"lie", "os"}, {"lies", "os"}, {"light", "istam"}, {"lightning", "giken"}, {"limb", "od"}, {"limbs", "od"}, {"lip", "mengmad"}, {"lips", "mengmad"}, {"lizard", "bungek"}, {"lobster", "zedot"}, {"lock", "thak"}, {"locks", "thak"}, {"length", "romek"}, {"lengths", "romek"}, {"loot", "utir"}, {"lord", "ilul"}, {"louse", "sosmil"}, {"lice", "sosmil"}, {"love", "aval"}, {"loves", "aval"}, {"lowness", "lushob"}, {"lunch", "asin"}, {"lunches", "asin"}, {"lung", "vunom"}, {"lungs", "vunom"}, {"lust", "nethgon"}, {"lute", "itur"}, {"lutes", "itur"}, {"lyric", "avan"}, {"lyrics", "avan"}, {"maggot", "mingus"}, {"maggots", "mingus"}, {"magic", "aroth"}, {"magicks", "aroth"}, {"man", "udos"}, {"mange", "imust"}, {"manges", "imust"}, {"marsh", "rinmol"}, {"marshes", "rinmol"}, {"martyr", "muzish"}, {"master", "kon"}, {"maw", "stul"}, {"mead", "thash"}, {"meads", "thash"}, {"meadow", "kenis"},
        {"meal", "fathkal"}, {"meal", "inob"}, {"meat", "ogril"}, {"meats", "igril"}, {"meditation", "an"}, {"meditations", "an"}, {"menace", "nalthish"}, {"mess", "ostesh"}, {"metal", "kel"}, {"midnight", "eddaz"}, {"mightiness", "aral"}, {"mile", "shar"}, {"mind", "ottan"}, {"minion", "shagul"}, {"mirror", "onul"}, {"mirrors", "onul"}, {"misery", "egeth"}, {"miseries", "egeth"}, {"mist", "sod"}, {"mists", "sod"}, {"mite", "dusak"}, {"mites", "dusak"}, {"mold", "ovus"}, {"molds", "ovus"}, {"mole", "gomok"}, {"monkey", "vankab"}, {"moon", "ilon"}, {"monger", "odes"}, {"moth", "alen"}, {"mother", "bobrur"}, {"mouse", "stoling"}, {"mouth", "dum"}, {"muck", "zagstok"}, {"mucks", "zagstoks"}, {"mud", "ol"}, {"muffin", "gatis"}, {"mule", "udler"}, {"murder", "usan"}, {"mush", "kavud"}, {"mushroom", "kirun"}, {"mushrooms", "kirun"}, {"music", "shasad"}, {"mystery", "shoveth"}, {"mysteries", "shoveth"}, {"myth", "lathon"}, {"nail", "um"}, {"nails", "um"}, {"nature", "egom"},
        {"natures", "egom"}, {"negator", "kez"}, {"nest", "ikul"}, {"net", "kib"}, {"nets", "kib"}, {"nettle", "rotik"}, {"nettles", "rotik"}, {"newt", "stoseth"}, {"night", "anan"}, {"nights", "anan"}, {"nightmare", "disuth"}, {"nightmares", "disuth"}, {"noble", "rithol"}, {"noose", "tezul"}, {"nooses", "tezul"}, {"nose", "otam"}, {"number", "nunok"}, {"numbers", "nunok"}, {"nut", "ishlum"}, {"nuts", "ishlum"}, {"oak", "kin"}, {"oaks", "kin"}, {"oar", "mebzuth"}, {"oars", "mebzuth"}, {"oat", "usib"}, {"oats", "usib"}, {"oblivion", "nar"}, {"ocean", "migrur"}, {"oceans", "migrur"}, {"omen", "dakon"}, {"one", "lod"}, {"onion", "anon"}, {"onions", "anon"}, {"ooze", "muved"}, {"oozes", "muved"}, {"orb", "vabok"}, {"orbs", "vabok"}, {"owl", "ritas"}, {"ox", "udril"}, {"pack", "shigos"}, {"packs", "shigos"}, {"pad", "dathnes"}, {"pads", "dathnes"}, {"page", "morul"}, {"pages", "morul"}, {"pain", "zulash"}, {"pains", "zulash"}, {"paint", "logem"}, {"paints", "logem"}, {"palm", "kulin"},
        {"palms", "kulin"}, {"panther", "gatin"}, {"pants", "ul"}, {"paper", "monom"}, {"papers", "monom"}, {"peace", "bisol"}, {"peach", "ginok"}, {"peaches", "ginok"}, {"pepper", "rumred"}, {"peppers", "rumred"}, {"phelgm", "ugeth"}, {"pig", "thuveg"}, {"pit", "gor"}, {"pits", "gor"}, {"pitch", "damol"}, {"plague", "elcur"}, {"plagues", "elcur"}, {"plant", "erok"}, {"plants", "erok"}, {"planter", "tok"}, {"plot", "im"}, {"plots", "im"}, {"pocket", "ret"}, {"pockets", "ret"}, {"poison", "inrus"}, {"poisons", "inrus"}, {"portal", "mistem"}, {"portals", "mistem"}, {"power", "midor"}, {"powers", "midor"}, {"prank", "nilgin"}, {"pranks", "nilgin"}, {"pregnancy", "merir"}, {"pride", "nikuz"}, {"priest", "kamik"}, {"prophecy", "arkoth"}, {"prophecies", "arkoth"}, {"prophet", "lashed"}, {"prowler", "kasith"}, {"puke", "ngathsesh"}, {"pulley", "besmar"}, {"pulp", "furgig"}, {"pulps", "furgig"}, {"punch", "nonub"}, {"punches", "nonub"}, {"pus", "megob"}, {"quake", "ushrir"},
        {"quakes", "usrir"}, {"queen", "esrel"}, {"quickness", "buket"}, {"quicknesses", "buket"}, {"quill", "nimak"}, {"quills", "nimak"}, {"rabbit", "lestus"}, {"rabbits", "lestus"}, {"rabble", "fullut"}, {"race", "arkim"}, {"rack", "led"}, {"rag", "unib"}, {"rags", "unib"}, {"rage", "ron"}, {"rages", "ron"}, {"rain", "udar"}, {"rains", "udar"}, {"ram", "detes"}, {"rampage", "umoz"}, {"rampages", "umoz"}, {"rat", "atem"}, {"raunch", "ezuk"}, {"ravager", "vozbel"}, {"raven", "toltot"}, {"rawness", "nar"}, {"rawnesses", "nar"}, {"razor", "stukos"}, {"razors", "stukos"}, {"reign", "ikud"}, {"reign", "ikud"}, {"rider", "emgash"}, {"rim", "tirist"}, {"ring", "athel"}, {"rip", "osdin"}, {"rips", "osdin"}, {"ripper", "kamut"}, {"rite", "selor"}, {"rites", "selor"}, {"river", "iger"}, {"rivers", "iger"}, {"rock", "id"}, {"rocks", "id"}, {"rogue", "astas"}, {"romance", "abir"}, {"romances", "abir"}, {"room", "mosus"}, {"rooms", "mosus"}, {"root", "odur"}, {"roots", "odur"},
        {"rose", "istbar"}, {"roses", "istbar"}, {"rot", "zodost"}, {"roughness", "dumat"}, {"ruin", "notlith"}, {"ruins", "notlith"}, {"ruler", "ilid"}, {"rumor", "tithleth"}, {"rumors", "tithleth"}, {"rust", "kezar"}, {"sabre", "ast"}, {"sabres", "ast"}, {"sack", "fath"}, {"sacks", "fath"}, {"saint", "tolun"}, {"salt", "nabid"}, {"salts", "nabid"}, {"salve", "sibrek"}, {"salves", "sibrek"}, {"sap", "thining"}, {"satin", "gasis"}, {"savage", "noglesh"}, {"savagery", "aroz"}, {"savageries", "aroz"}, {"savior", "tamol"}, {"scab", "nanul"}, {"scabs", "nanul"}, {"scar", "urrith"}, {"scars", "urrith"}, {"scorpion", "askak"}, {"scratch", "kes"}, {"scratches", "kes"}, {"scourge", "abshoth"}, {"scream", "ubas"}, {"screams", "ubas"}, {"scum", "angish"}, {"sea", "allas"}, {"seas", "allas"}, {"seal", "gembish"}, {"seals", "gembish"}, {"seal", "urvad"}, {"seals", "urvad"}, {"seam", "fel"}, {"seams", "fel"}, {"season", "ingul"}, {"seasons", "ingul"}, {"secret", "nekut"}, {"secrets", "nekut"},
        {"seduction", "genlath"}, {"seductions", "genlath"}, {"seducer", "shulmuk"}, {"seed", "lenod"}, {"seeds", "lenod"}, {"seer", "abras"}, {"seizure", "asol"}, {"serpent", "shethel"}, {"servant", "urnut"}, {"sever", "zursal"}, {"sewer", "othsal"}, {"sewers", "othsal"}, {"shadow", "shedim"}, {"shadows", "shedim"}, {"shaft", "arak"}, {"shafts", "arak"}, {"shank", "tizot"}, {"shanks", "tizot"}, {"shark", "taran"}, {"sheen", "otik"}, {"sheens", "otik"}, {"shell", "kerlig"}, {"shells", "kerlig"}, {"shelter", "lened"}, {"shelters", "lened"}, {"shield", "sodel"}, {"shields", "sodel"}, {"ship", "zuglar"}, {"ships", "zuglar"}, {"show", "nast"}, {"shows", "nast"}, {"shred", "uvoth"}, {"shreds", "uvoth"}, {"shriek", "mivid"}, {"shrieks", "mivid"}, {"sick", "kafash"}, {"sickness", "ngumrash"}, {"sicknesses", "ngumrash"}, {"siege", "zokun"}, {"sieges", "zokum"}, {"silence", "eshom"}, {"silences", "eshom"}, {"silk", "nesteth"}, {"silks", "nesteth"}, {"silkiness", "thebil"}, {"silt", "ammesh"},
        {"silver", "ral"}, {"silvers", "ral"}, {"sin", "reksas"}, {"sins", "reksas"}, {"sinew", "gesis"}, {"sinews", "gesis"}, {"song", "osal"}, {"songs", "osal"}, {"sister", "anir"}, {"skirt", "nabreth"}, {"skirts", "nabreth"}, {"skunk", "rungak"}, {"skull", "nekol"}, {"skulls", "nekol"}, {"sky", "anriz"}, {"skies", "anriz"}, {"slaughter", "kosh"}, {"slaughters", "kosh"}, {"slave", "noth"}, {"slayer", "tharnas"}, {"slime", "bagoz"}, {"slimes", "bagoz"}, {"sling", "bim"}, {"slit", "sakil"}, {"slits", "sakil"}, {"sliver", "rasuk"}, {"slivers", "rasuk"}, {"sloth", "gazot"}, {"slug", "tozor"}, {"slugs", "gazot"}, {"smile", "kal"}, {"smiles", "kal"}, {"smith", "eshtan"}, {"smoke", "mezum"}, {"smoothness", "umar"}, {"snack", "geles"}, {"snacks", "geles"}, {"snake", "therleth"}, {"sneer", "tinan"}, {"snot", "zekrim"}, {"snots", "zekrim"}, {"soil", "adur"}, {"soils", "adur"}, {"soldier", "ezar"}, {"soot", "bonun"}, {"sorrow", "egur"}, {"sorrows", "egur"}, {"soul", "unol"}, {"sound", "vod"},
        {"sounds", "vod"}, {"spasm", "debish"}, {"spasms", "debish"}, {"spawn", "bushos"}, {"spear", "lokum"}, {"spears", "lokum"}, {"spell", "thortith"}, {"spells", "thortith"}, {"spice", "omat"}, {"spices", "omat"}, {"spider", "sethal"}, {"spiders", "sethal"}, {"spike", "thocit"}, {"spikes", "thocit"}, {"spine", "lurit"}, {"spines", "lurit"}, {"spirit", "ubal"}, {"spirits", "ubal"}, {"spit", "ostob"}, {"spittle", "lashid"}, {"spoils", "usur"}, {"spoon", "kob"}, {"spoons", "kob"}, {"spring", "kigok"}, {"springs", "kigok"}, {"spy", "estrith"}, {"squid", "gongith"}, {"staff", "nomal"}, {"talker", "oltud"}, {"stance", "savot"}, {"stances", "savot"}, {"star", "vir"}, {"steed", "dustik"}, {"starvation", "shistsak"}, {"steel", "deler"}, {"stench", "aztong"}, {"stench", "aztong"}, {"stick", "sholil"}, {"sticks", "sholil"}, {"stone", "lam"}, {"stones", "lam"}, {"storm", "togal"}, {"storms", "togal"}, {"strangeness", "mot"}, {"strangenesses", "mot"}, {"strap", "niles"}, {"straps", "niles"},
        {"straw", "atith"}, {"straw", "atith"}, {"stray", "reg"}, {"strays", "reg"}, {"strength", "emen"}, {"strike", "abod"}, {"strikes", "abod"}, {"stroke", "sat"}, {"strokes", "sat"}, {"stunt", "timad"}, {"stunts", "timad"}, {"style", "tunur"}, {"styles", "tunur"}, {"subordinate", "idgag"}, {"sucker", "eb"}, {"suckers", "eb"}, {"suffering", "omshit"}, {"sufferings", "omshit"}, {"sugar", "ibes"}, {"sugars", "ibes"}, {"summer", "isram"}, {"sun", "ad"}, {"supper", "nis"}, {"surprise", "stot"}, {"surprises", "stot"}, {"swamp", "ogred"}, {"swamps", "ogred"}, {"sweat", "sined"}, {"sweetness", "tecak"}, {"sweetnesses", "tecak"}, {"swine", "obash"}, {"sword", "dastot"}, {"swords", "dastot"}, {"syrup", "udib"}, {"syrups", "udib"}, {"taker", "enkos"}, {"tail", "kesh"}, {"tails", "kesh"}, {"talon", "kidet"}, {"talons", "kidet"}, {"tar", "ob"}, {"tarnish", "thilseg"}, {"tempest", "akmesh"}, {"tempests", "akmesh"}, {"tear", "vim"}, {"tears", "vim"}, {"terror", "angzak"}, {"terrors", "angzak"},
        {"thief", "gakit"}, {"thirst", "recus"}, {"thirsts", "recus"}, {"thorn", "kurik"}, {"thorns", "kurik"}, {"thrall", "unkil"}, {"throat", "erith"}, {"thrower", "arros"}, {"thunder", "amud"}, {"tick", "nobgost"}, {"ticks", "nobgost"}, {"tightness", "lid"}, {"tightnesses", "lid"}, {"time", "ashok"}, {"times", "ashok"}, {"toad", "nod"}, {"toe", "nin"}, {"toes", "nin"}, {"tomb", "rakust"}, {"tombs", "rakust"}, {"tome", "melbil"}, {"tomes", "melbils"}, {"tongue", "nol"}, {"tongues", "nol"}, {"tooth", "raz"}, {"teeth", "raz"}, {"torment", "distust"}, {"torments", "distust"}, {"touch", "tat"}, {"touches", "tat"}, {"tour", "sigun"}, {"tours", "sigun"}, {"tower", "urdim"}, {"towers", "urdim"}, {"trail", "kalan"}, {"trails", "kalan"}, {"trance", "shelret"}, {"trances", "shelret"}, {"trap", "iggal"}, {"traps", "iggal"}, {"trash", "redreg"}, {"treasure", "idrath"}, {"treasures", "idrath"}, {"treat", "datlad"}, {"treats", "datlad"}, {"treaty", "ilral"}, {"treaties", "ilral"},
        {"trench", "borik"}, {"trenches", "borik"}, {"tribe", "meden"}, {"trick", "vafig"}, {"tricks", "vafig"}, {"trickery", "tizen"}, {"trim", "dizesh"}, {"trouble", "kobem"}, {"troubles", "kobem"}, {"tulip", "shilrar"}, {"tulips", "shilrar"}, {"tumor", "messog"}, {"tumours", "messog"}, {"turmoil", "bukith"}, {"turmoils", "bukith"}, {"tusk", "bufut"}, {"tusks", "bufut"}, {"twilight", "ingtak"}, {"twine", "damor"}, {"twist", "gim"}, {"ulcer", "mengib"}, {"ulcers", "mengib"}, {"uncle", "mer"}, {"urn", "vucar"}, {"urns", "vucar"}, {"vandal", "tufrug"}, {"vegetable", "segam"}, {"vegetables", "segam"}, {"velvet", "zamoth"}, {"venom", "zamoth"}, {"venoms", "zamoth"}, {"vermin", "bomik"}, {"violator", "razmer"}, {"violence", "liruk"}, {"viper", "zenon"}, {"vipers", "zenon"}, {"voice", "okol"}, {"voices", "okol"}, {"void", "torir"}, {"voids", "torir"}, {"volcano", "stodir"}, {"volcanoes", "stodir"}, {"vomit", "oggon"}, {"vulture", "tikis"}, {"wail", "unos"}, {"wails", "unos"},
        {"wanderer", "legon"}, {"war", "alnis"}, {"warrior", "ikor"}, {"wasp", "tathtak"}, {"wasps", "tathtak"}, {"waste", "lidod"}, {"wastes", "lidod"}, {"watch", "azin"}, {"watches", "azin"}, {"watchfulness", "isden"}, {"wave", "uker"}, {"waves", "uker"}, {"waviness", "kussad"}, {"weasel", "bamgus"}, {"weaver", "adril"}, {"weed", "koshmot"}, {"weeds", "koshmot"}, {"weight", "al"}, {"weights", "al"}, {"weird", "umgush"}, {"wheat", "kil"}, {"wheats", "kil"}, {"wheel", "kol"}, {"wheels", "kol"}, {"whip", "bomrek"}, {"whips", "bomrek"}, {"whisky", "atil"}, {"whiskies", "atil"}, {"whisper", "iklist"}, {"whispers", "iklist"}, {"wickedness", "lish"}, {"wildness", "omrist"}, {"will", "ud"}, {"wills", "ud"}, {"wing", "fesh"}, {"wings", "fesh"}, {"winter", "akath"}, {"wisp", "lim"}, {"wisps", "lim"}, {"witch", "damid"}, {"wonder", "anur"}, {"wonders", "anur"}, {"wood", "lolum"}, {"woods", "lolum"}, {"work", "ducim"}, {"works", "ducim"}, {"worm", "vesrul"}, {"worms", "vesrul"},
        {"wraith", "urosh"}, {"wrath", "akith"}, {"wretch", "lerush"}, {"yarn", "ethir"}, {"yarns", "ethir"}, {"year", "id"}, {"years", "id"}, {"yearling", "budam"}, {"yore", "okang"}, {"youth", "rilem"}, {"zeal", "kizest"}, {"zealot", "kebosh"}, {"zephyr", "shesam"}};
    }
}
